# Problem 1 

In [4]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
a=np.array([16,7,3,8,5])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(a))

[ 3  5  7  8 16]


# Problem 2

In [37]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
x=np.array([10,15,30,45,60])
print(x)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
y=np.arange(5,15)
print(y)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
z=np.arange(5,100,5)
print(z)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
np.ones(10)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
t=np.linspace(0,100,5)
print(t)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
v=np.random.randint(10,30, size=5)
print(v)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
c=np.random.uniform(-1,1, size=10)
print(c)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
b=np.random.randint(10,50, size=(3,5))
print(b)


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(b.sum(axis=0))
print(b.sum(axis=1))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(np.min(b))
print(np.max(b))
print(np.mean(b))
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_deger=b[0,0]
for i in range(b.shape[0]):
    for z in range(b.shape[1]):
        if b[i,z]>max_deger:
            max_deger=b[i,z]
print(max_deger)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
d=np.random.randint(10,20, size=8)
print(d)
print(d[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(d[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
d1=d.reshape(2,4)
print(d1)
print(d1[0,:])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(d1[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(d1[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(d1**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
e=np.random.randint(-50,50,size=[5,5])
print(e)
e1=e[e>0]
print(e1[e1%2==0])

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[  0.  25.  50.  75. 100.]
[25 16 21 12 12]
[-0.72140474  0.85906259 -0.1445865   0.20056483  0.55610407  0.20634041
 -0.82652881  0.40281674 -0.49896442  0.16616965]
[[21 34 16 28 45]
 [17 42 19 24 22]
 [25 31 34 46 33]]
[ 63 107  69  98 100]
[144 124 169]
16
46
29.133333333333333
46
[19 13 18 12 19 13 16 11]
[19 13 18]
[11 16 13 19 12 18 13 19]
[[19 13 18 12]
 [19 13 16 11]]
[19 13 18 12]
16
[19 19]
[[361 169 324 144]
 [361 169 256 121]]
[[ 25 -37 -41  20  41]
 [-30 -12 -10  49 -33]
 [ 25 -12  18 -10 -44]
 [-13  15  14 -43 -15]
 [ -6  44 -44 -38  22]]
[20 18 14 44 22]
