# Problem 1

In [11]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a=np.random.randint(10, size=5)
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.shape)
# 4 - matris'i yeniden boyutlandırın
b=a.reshape(5,1)
print(b)
# 5 - matris'in boyut sayısını öğrenin
print(b.ndim)

[5 7 8 0 5]
(5,)
[[5]
 [7]
 [8]
 [0]
 [5]]
2


# Problem 2

In [21]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
x=np.arange(1,10,2)
print(x)
# 2 - Oluşturduğunuz matrisi parçalayın
print(np.hsplit(x,[2]))
# 3 - Parçalanmış matrisleri birleştirin
arrays=[np.array([1, 3]), np.array([5, 7, 9])]
print(np.concatenate(arrays))

[1 3 5 7 9]
[array([1, 3]), array([5, 7, 9])]
[1 3 5 7 9]


# Problem 3

In [26]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
v=np.random.randint(5,100,10)
print(v)
# 2 - matris'in özelliklerini inceleyin
print(v.shape)
print(v.ndim)
print(v.dtype)
print(v.size)

[18 86 14 71 46 79 23 78 74 55]
(10,)
1
int32
10
